config/routes.rb
OuiShareFest::Application.routes.draw do

  resources :traductions
  resources :individual_types

  # SetLanguage routes
  namespace :set_language do
    get :set_new_language, :as => "set_new_language"
  end
  # get 'set_language/set_new_language', :as => "set_new_language"

  # Admin routes
  resources :admin, only: [:index] do
    collection do
      get :export_users
      get :export_newsletter_subscribers
      get :users_list
      get :settings_list 
      get :strong_auth_access_page
      get :individuals_list
      get :individual_types_list
      get :restart_nginx_server
      post :validate_strong_auth    
    end
    member do
      get :individual_type
      post :toggle_admin
      post :toggle_setting
    end
  end

  resources :individuals

  # Devise routes  
  devise_for :users, :skip => [:sessions, :registrations], :path => ''
  devise_scope :user do
    get '/register', :to => 'devise/registrations#new', :as => 'user_registration'
    post '/register', :to => 'devise/registrations#create'
    get '/login', :to => 'devise/sessions#new', :as => 'new_user_session'
    post '/login', :to => 'devise/sessions#create'
    delete '/logout', :to => 'devise/sessions#destroy'
    # get '/password/change', :to => 'devise/registrations#edit', :as => 'change_password'
    # TODO: delete the route of cancel account, by delete defaut routes of registrations (:skip => [:registrations]) and only keeping custom ones
    end
  
  resources :users, only: [:index, :show, :edit, :update]

  # Home routes
  root :to => 'home#index'

  namespace :home, :path => nil do
    get :faq
    # get :contact
    # post :contact, :action => :contact_email
    get :site_off
    get :program
    get :about
    get :participants
    get :join
    get :fest2014
    # get :stories
    post :newsletter_collect_email
  end

  resources :stories, :only => [:index, :show], :singular => :story

  namespace :me do
    get :dashboard
    get :preferences
    get :edit_profile   
    get :change_password
    put :apply_change_password
    put :update_profile  
  end

  get '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure' 
    
end

app/models/individual.rb
class Individual < ActiveRecord::Base
  attr_accessible :birthday, :company_name, :description, :first_name, :function, :last_name, :individual_type_id, :twitter_account, :url, :email
  attr_accessible :attachment, :slug, :display_order
  Paperclip.interpolates :attachment do |attachment, style|
  attachment.instance.attachment_file_name # or whatever you've named your User's login/username/etc. attribute
  end

  Paperclip.interpolates :class_name_individual do |attachment, style|
  attachment.instance.class.name # or whatever you've named your User's login/username/etc. attribute
  end

  has_attached_file :attachment, :default_url => "/assets/individual_default_avatar-:style.png", 
  :styles => {mini: '30x30#',small: '100x100>',medium: '300x300>',custom: '220x220#', partner_size: 'x138'},
  :path => ":rails_root/public/system/:class_name_individual/:id/attachment/:style_:attachment",
  :url => "/system/:class_name_individual/:id/attachment/:style_:attachment"

  # belongs_to :individual_type, :class_name => "IndividualType", :foreign_key => :individual_type_id

  has_many :individual_types_assocs, :class_name => "IndividualTypeAssociation", :foreign_key => :individual_id, :dependent => :delete_all
  has_many :individual_types, :class_name => "IndividualType", :through => :individual_types_assocs
  
  has_many :event_indiv_assoc, :class_name => "EventIndividualAssociation", :foreign_key => :individual_id
  has_many :events, :class_name => "Event", :through => :event_indiv_assoc

  before_create :generate_slug
  after_save :export_to_yaml
  after_destroy :delete_from_yaml


  def export_to_yaml
    if description_changed?
      d = YAML::load_file(ENV['YAML_INDIVIDUALS_FILE_PATH']) #Load
      
      if d['en']['individuals_biography'].blank?
        d['en']['individuals_biography'] = {}
      end            
      d['en']['individuals_biography'][self.slug] = self.description
      
      
      File.open(ENV['YAML_INDIVIDUALS_FILE_PATH'], 'w') do |f|
        f.write d.to_yaml
      end
      #connect_and_push_to_transifex()
    end
  end

  def delete_from_yaml
    d = YAML::load_file(ENV['YAML_INDIVIDUALS_FILE_PATH'])
    if !d['en']['individuals_biography'][self.slug].blank?
        d['en']['individuals_biography'].delete self.slug
    end   
    
    File.open(ENV['YAML_INDIVIDUALS_FILE_PATH'], 'w') do |f|
      f.write d.to_yaml
    end
    #connect_and_push_to_transifex()
  end
  
  def generate_slug    
    if self.first_name != '' && self.last_name != '' && !self.slug 
      if Individual.where(:slug => self.fullname.parameterize).count > 0
        n = 1
        while Individual.where(:slug => "#{self.fullname.parameterize}-#{n}").count > 0
          n += 1
        end
        self.slug = "#{self.fullname.parameterize}-#{n}"

      else
        self.slug = self.fullname.parameterize
        
      end
    end  
  end

  def add_to_current_event
    
    event = Event.find_by_edition_year(ENV["OUISHARE_FEST_EVENT_YEAR"])
   
    if !EventIndividualAssociation.find_by_event_id_and_individual_id(event.id, self.id)
      
      self.individual_types.each do |indiv_type|
        assoc = {
          :event_id => event.id,
          :individual_type_id => indiv_type.id,
          :individual_id => self.id
        }
        EventIndividualAssociation.create(assoc)

      end 
    end   
    
  end

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
  # function: full_name
  # Return the full name of an individual
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
  def fullname
    @fullname = ""
    if !self.first_name.blank?
      @fullname = self.first_name
    end

    if !self.last_name.blank?
      @fullname += ' ' + self.last_name
    end

    @fullname
  end

  def self.get_partners_by_function
    @partners_array = []
    @partners = Individual.joins(:individual_types).merge(IndividualType.where(:title => "Partners"))
    @functions = @partners.select("DISTINCT(function)").order("function ASC")
    @functions.each do |function|
      @partners = Individual.where(:function => function.function)
      @partners_array.push({function.function => @partners})
      
    end    
    @partners_array
  end


  private 

  def connect_and_push_to_transifex
    base_url = ENV['TRANSIFEX_BASE_URL']
       
    request_response = nil    
    d = YAML::load_file(ENV['YAML_INDIVIDUALS_FILE_PATH'])
    file = {}
    file['content'] = d.to_yaml
    file = file.to_json

    request_url = ENV['TRANSIFEX_INDIVIDUALS_URL']
    uri = URI(base_url + request_url)

    res = Net::HTTP.start(uri.host, 80) do |http|
      request = Net::HTTP::Put.new uri.request_uri
      request.basic_auth ENV['TRANSIFEX_CREDENTIAL_LOGIN'], ENV['TRANSIFEX_CREDENTIAL_SECRET']
      request.content_type = "application/json"
      request.body = file
      
      response = http.request request
     
      request_response = response.body
      
    end
    return request_response
  end

end

app/models/individual_type.rb
class IndividualType < ActiveRecord::Base
  attr_accessible :title 
  
  has_many :individual_types_assocs, :class_name => "IndividualTypeAssociation", :foreign_key => :individual_type_id, :dependent => :delete_all
  has_many :individuals, :class_name => "Individual", :through => :individual_types_assocs

  def get_member_number
    self.individuals.count    
  end

  def get_members
    self.individuals.order('display_order ASC')    
  end

  def to_param
    self.title    
  end
end

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
  before_filter :authenticate_admin! , :except => [:index, :show]
  # TODO : 
  # Ajout / Suppression attachment, birthday, tous les autres champs ...
  # before_filter Admin
  # function pour récupérer la liste des Individuals d'un certain type
  # Préciser le groupe de la personne avec une liste déroulante

  def index
    @individuals = Individual.all
  end

  def show
    @individual = Individual.find(params[:id])
  end

  def new
    @individual = Individual.new
    @is_checked = params[:is_checked]
  end

  def create
    # @individual = Individual.new(params[:individual])

    if @individual = Individual.create(params[:individual])         
      updateIndividualTypes(params[:individual_types])     
      @individual.add_to_current_event   
      redirect_to individuals_list_admin_index_path, :notice => 'Creation successfull'
    else
      redirect_to individuals_list_admin_index_path, :alert => 'An error occured'
    end

  end

  def edit
    @individual = Individual.find(params[:id])
  end

  def update

    @individual = Individual.find(params[:id])
    if @individual.update_attributes(params[:individual])      
      updateIndividualTypes(params[:individual_types])      
      redirect_to individuals_list_admin_index_path, :notice => 'Update successfull'
    else
      redirect_to individuals_list_admin_index_path, :alert => 'An error occured'
    end

  end

  def destroy
    @individual = Individual.find(params[:id])
    if @individual.destroy 
      redirect_to individuals_list_admin_index_path, :notice => 'Deleted successfully'
    else
      redirect_to individuals_list_admin_index_path, :alert => 'An error occured'
    end
  end
  private

  def updateIndividualTypes(params=[])
     
    params.each do |type|
      if !IndividualTypeAssociation.find_by_individual_id_and_individual_type_id(@individual.id, type)
        IndividualTypeAssociation.create(:individual_id => @individual.id, :individual_type_id => type)
      end
    end  

    IndividualType.all.each do |type|      
      if(IndividualTypeAssociation.find_by_individual_id_and_individual_type_id(@individual.id, type.id)&& !(params.include?(type.id.to_s)))
        indiv_type =IndividualTypeAssociation.find_by_individual_id_and_individual_type_id(@individual.id, type.id)
        indiv_type.destroy
      end
    end
  end
end

app/helpers/individual_helper.rb
module IndividualHelper
end

app/views/individuals/partials/_index_partial.html.haml
=render '/individuals/partials/individual_list', :individuals => @individuals, :admin_panel => true

app/views/individuals/partials/_individual_list.html.haml
%table.table.table-hover.table-nonfluid
  %thead
    %tr
      %th #
      %th Identity
      %th Information
      %th Description
      - if admin_panel
        %th Actions
  %tbody
    - individuals.each do |individual|
      %tr
        %td
          = image_tag individual.attachment.url(:small)
        %td

          = individual.fullname
          - if !individual.email.blank?
            %br
            = individual.email
          - if !individual.birthday.blank?
            %br
            Birthday : 
            = individual.birthday           
        %td
          - if !individual.twitter_account.blank?
            %a{href: "http://www.twitter.com/" + individual.twitter_account, target: "_blank"}
              = "@" + individual.twitter_account
          - if !individual.company_name.blank?
            %br
            = individual.company_name
          - if !individual.function.blank?
            %br
            = individual.function
          - if !individual.url.blank?
            %br
            %a{href: individual.url, target: "_blank"}
              = individual.url
        %td
          - if !individual.description.blank?
            = truncate(individual.description, :length  => 100)
        %td 
          = link_to 'Show', individual_path(individual)
          - if admin_panel
            %br
            = link_to 'Edit', edit_individual_path(individual)
            %br
            = link_to 'Delete', individual_path(individual), 'data-method' => :delete, :confirm => 'Are you sure ?'        

app/views/individuals/partials/_partners_display.html.haml
- array_buffer = []
- partner_number = 1
- test = true
- special = ''
- three_col = 1
- placement = ''

- if !partners.blank?
  - if important_partners_display
    - partners.first(important_partners_count).each do |partner|
      - array_buffer.push(partner)
    - remain = important_partners_count % 4
    - if remain > 0
      .row.centered
        - array_buffer.first(remain).each do |partner|
          - if partner.first_name == 'Orange'
            - special = "tooltip.orange"
          - if partner.first_name == 'La Poste'
            - special = "tooltip.laposte"
          - if partner.first_name == 'Castorama'
            - special = "tooltip.castorama"
          - if remain == 1
            .col-lg-12
              %a{:href => partner.url, :target => "_blank", :class => "special_tooltip", :data => {'original-title' => t(special), 'placement' => 'right'}}
                %img.img-responsive.display-inline{:alt => partner.first_name, :src => partner.attachment.url(:medium)}
          - elsif remain == 2
            .col-lg-6
              %a{:href => partner.url, :target => "_blank", :class => "special_tooltip", :data => {'original-title' => t(special), 'placement' => 'right'}}
                %img.img-responsive.display-inline{:alt => partner.first_name, :src => partner.attachment.url(:medium)}
          - elsif remain == 3
            - if three_col == 3
              - placement = 'left'
            - else
              - placement = 'right'
            .col-lg-4
              - if !special.blank?
                %a{:href => partner.url, :target => "_blank", :class => "special_tooltip", :data => {'original-title' => I18n.t(special, :default => ""), 'placement' => placement}}
                  %img.img-responsive.display-inline{:alt => partner.first_name, :src => partner.attachment.url(:medium)}
              - else
                %a{:href => partner.url, :target => "_blank", :class => "special_tooltip", :data => {'original-title' => "", 'placement' => placement}}
                  %img.img-responsive.display-inline{:alt => partner.first_name, :src => partner.attachment.url(:medium)}                
            - three_col = three_col + 1
          - array_buffer.delete_at(0)
      %hr
      %br
      %br

    - while !array_buffer.empty? do
      .row.centered
        - array_buffer.first(4).each do |partner|
          .col-lg-3
            %a{:href => partner.url, :target => "_blank"}
              %img.img-responsive.display-inline{:alt => partner.first_name, :src => partner.attachment.url(:medium)}
          - array_buffer.delete_at(0)
    

  - else
    - important_partners_count = 0
  - partners.last(partners.size-important_partners_count).each do |partner|
    - array_buffer.push(partner)      
    - if partner_number % 6 == 0 || partner_number == (partners.count - important_partners_count)
      .row.centered
        - array_buffer.each do |partner|
          .col-lg-2.home_partners
            %a{:href => partner.url, :target => "_blank"}
              %img.img-responsive.display-inline{:alt => partner.first_name, :src => partner.attachment.url(:medium)}
              
        - array_buffer.clear
    - partner_number += 1

app/views/individuals/partials/_speaker_display.html.haml
.ch-item{style: "background-image:url(" + speaker.attachment.url(:custom) + ")"}
  .ch-info
    - if !speaker.twitter_account.blank?
      %a{href: "http://www.twitter.com/" + speaker.twitter_account, target: "_blank"}
        %h3
          = speaker.fullname
    - else
      %h3
        = speaker.fullname
    - if !speaker.twitter_account.blank?
      %p
        %a{href: "http://www.twitter.com/" + speaker.twitter_account, target: "_blank"}
          = "@" + speaker.twitter_account
%h6
  .white
    %b
      = speaker.fullname
  - if !speaker.company_name.blank?
    %small
      %a{href: speaker.url, target: "_blank"}
        = speaker.company_name
  - else
    %br
  

app/views/individuals/partials/_team_member_display.html.haml
.ch-item{style: "background-image:url(" + team_member.attachment.url(:custom) + ")"}
  .ch-info
    - if !team_member.twitter_account.blank?
      %a{href: "http://www.twitter.com/" + team_member.twitter_account, target: "_blank"}
        %h3
          = team_member.function
    / - else
    /   %h3
    /     = team_member.fullname
    - if !team_member.twitter_account.blank?
      %p
        %a{href: "http://www.twitter.com/" + team_member.twitter_account, target: "_blank"}
          = "@" + team_member.twitter_account
%h6
  %b
  = team_member.fullname
  %br/
  - if !team_member.description.blank?
    %small
      = team_member.description
  -else
    %br
  / %br/
  / %br/
  / - if !team_member.slug.blank?
  /   %small
  /     = t('individuals_biography.' + team_member.slug)