config/routes.rb
OuiShareFest::Application.routes.draw do

  resources :traductions
  resources :individual_types

  # SetLanguage routes
  namespace :set_language do
    get :set_new_language, :as => "set_new_language"
  end
  # get 'set_language/set_new_language', :as => "set_new_language"

  # Admin routes
  resources :admin, only: [:index] do
    collection do
      get :export_users
      get :export_newsletter_subscribers
      get :users_list
      get :settings_list 
      get :strong_auth_access_page
      get :individuals_list
      get :individual_types_list
      get :restart_nginx_server
      post :validate_strong_auth    
    end
    member do
      get :individual_type
      post :toggle_admin
      post :toggle_setting
    end
  end

  resources :individuals

  # Devise routes  
  devise_for :users, :skip => [:sessions, :registrations], :path => ''
  devise_scope :user do
    get '/register', :to => 'devise/registrations#new', :as => 'user_registration'
    post '/register', :to => 'devise/registrations#create'
    get '/login', :to => 'devise/sessions#new', :as => 'new_user_session'
    post '/login', :to => 'devise/sessions#create'
    delete '/logout', :to => 'devise/sessions#destroy'
    # get '/password/change', :to => 'devise/registrations#edit', :as => 'change_password'
    # TODO: delete the route of cancel account, by delete defaut routes of registrations (:skip => [:registrations]) and only keeping custom ones
    end
  
  resources :users, only: [:index, :show, :edit, :update]

  # Home routes
  root :to => 'home#index'

  namespace :home, :path => nil do
    get :faq
    # get :contact
    # post :contact, :action => :contact_email
    get :site_off
    get :program
    get :about
    get :participants
    get :join
    get :fest2014
    # get :stories
    post :newsletter_collect_email
  end

  resources :stories, :only => [:index, :show], :singular => :story

  namespace :me do
    get :dashboard
    get :preferences
    get :edit_profile   
    get :change_password
    put :apply_change_password
    put :update_profile  
  end

  get '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure' 
    
end

app/views/admin/_settings.html.haml
.container
  .row
    - @settings.each do |setting|
      = define_setting_action(setting)
  %br
  .row    
    %button{:type => "button", :class => "btn btn-warning", :id => "restart_server_btn"}
      Restart server      
  = render '/modals/server_loader'

app/views/admin/export_newsletter_subscribers.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Subscription Date</Data></Cell>
      </Row>
    <% @newsletter_subscribers.each do |newsletter_subscriber| %>
      <Row>
        <Cell><Data ss:Type="String"><%= newsletter_subscriber.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= newsletter_subscriber.created_at %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/export_users.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Nom</Data></Cell>
        <Cell><Data ss:Type="String">Prenom</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Date d'inscription</Data></Cell>
      </Row>
    <% @users.each do |user| %>
      <Row>
        <Cell><Data ss:Type="String"><%= user.last_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.first_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.created_at %></Data></Cell>        
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/admin/index.html.haml
.container.admin-container
  .row
    .col-md-12
      %h4
        Admin Dashboard     

.container
  / upper section
  .row
    .col-md-3
      = render '/admin/partial/menu', :active => 'admin_index'
      
    .col-md-9
      %strong
        %i.glyphicon.glyphicon-dashboard
        Admin Dashboard
      %hr/
      %i.glyphicon.glyphicon-list
      = link_to "Users list - CSV", export_users_admin_index_path(:format => :csv)
      %br
      %i.glyphicon.glyphicon-list
      = link_to "Users list- Excel", export_users_admin_index_path(:format => :xls)      
      %br
      %br
      %i.glyphicon.glyphicon-link
      = link_to "See Users list", users_list_admin_index_path

      %br
      / %i.glyphicon.glyphicon-list
      / = link_to "Newsletter Subscribers- CSV", export_newsletter_subscribers_admin_index_path(:format => :csv)
      %br
      %i.glyphicon.glyphicon-list
      = link_to "Newsletter Subscribers- Excel", export_newsletter_subscribers_admin_index_path(:format => :xls)
      
      = render "settings", :settings => @settings

%footer.text-center
#addWidgetModal.modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4.modal-title Add Widget
      .modal-body
        %p Add a widget stuff here..
      .modal-footer
        %a.btn{href: "#"} Close
        %a.btn.btn-primary{href: "#"} Save changes
    / /.modal-content
  / /.modal-dalog
/ /.modal

app/views/admin/individual_type.html.haml
.container.admin-container
  .row
    .col-md-12
      %h1 
        Manage
        = @individual_type.title
.container
  / upper section
  .row
    .col-md-3
      = render '/admin/partial/menu', :active => 'individuals', :active_sub_panel => @individual_type.title
      
    .col-md-9
      = render "/individual_types/partials/show_partial", :admin_panel => true

app/views/admin/individual_types_list.html.haml
.container.admin-container
  .row
    .col-md-12
      %h1 
        Manage Individual Types
.container
  .row
    .col-md-3
      = render '/admin/partial/menu', :active => 'individual_types'
    .col-md-9    
      %b
        =link_to new_individual_type_path do
          %i.glyphicon.glyphicon-plus-sign
          Create a new Individual Type
      %hr/
      %br
      = render '/individual_types/partials/index_partial', :admin_panel => true
      

      

app/views/admin/individuals_list.html.haml
.container.admin-container
  .row
    .col-md-12
      %h1 
        Manage Individuals
      
.container      
  .row
    .col-md-3
      = render '/admin/partial/menu', :active => 'individuals'
    .col-md-9
      %strong
        = link_to new_individual_path do
          %i.glyphicon.glyphicon-plus-sign
          Create new individual
      %hr      
      %br
      .table-index-container
        = render "/individuals/partials/index_partial", :admin_panel => true

app/views/admin/manage_traductions.html.haml
.container.admin-container
  %h1
    Manage Traductions

app/views/admin/settings_list.html.haml
.container.admin-container
  .row
    .col-md-12
      %h1
        Traductions index
.container
  .row
    .col-md-3
      = render '/admin/partial/menu', :active => 'settings_list'
    .col-md-9  
      %strong        
        %i.glyphicon.glyphicon-link
        Settings list
      %hr/
      %br
      = render "settings", :settings => @settings

app/views/admin/strong_auth_access_page.html.haml
.container.admin-container
  %h1
    Code Page

  You have received an email containing the code you have to enter below to confirm your access to the admin panel.

  = form_tag validate_strong_auth_admin_index_path do 
    .form-group.row
      =text_field_tag :admin_code, "", :class => "form-control"
    .form-group.row
      =submit_tag "Send Code"

app/views/admin/users_list.html.haml
.container.admin-container
  .row
    .col-md-12
      %h1 
        Users list

.container
  .row
    .col-md-3
      = render '/admin/partial/menu', :active => 'users_list'
    .col-md-9    
      %strong
        %i.glyphicon.glyphicon-dashboard
        User's list
      %hr/
      %br
      %table.table
        %thead
          %th id
          %th First name
          %th Last name
          %th Email
          %th Manage Admin
        %tbody
          - @users.each do |user|
            %tr
              %td 
                = user.id
              %td 
                = user.first_name
              %td 
                = user.last_name
              %td 
                = user.email
              %td 
                - if user != current_user
                  - if user.is_admin 
                    = button_to 'Revoke admin', toggle_admin_admin_path(user), :class => "btn btn-warning"
                  - else
                    = button_to 'Grant admin', toggle_admin_admin_path(user), :class => "btn btn-success"