config/routes.rb
OuiShareFest::Application.routes.draw do

  resources :traductions
  resources :individual_types

  # SetLanguage routes
  namespace :set_language do
    get :set_new_language, :as => "set_new_language"
  end
  # get 'set_language/set_new_language', :as => "set_new_language"

  # Admin routes
  resources :admin, only: [:index] do
    collection do
      get :export_users
      get :export_newsletter_subscribers
      get :users_list
      get :settings_list 
      get :strong_auth_access_page
      get :individuals_list
      get :individual_types_list
      get :restart_nginx_server
      post :validate_strong_auth    
    end
    member do
      get :individual_type
      post :toggle_admin
      post :toggle_setting
    end
  end

  resources :individuals

  # Devise routes  
  devise_for :users, :skip => [:sessions, :registrations], :path => ''
  devise_scope :user do
    get '/register', :to => 'devise/registrations#new', :as => 'user_registration'
    post '/register', :to => 'devise/registrations#create'
    get '/login', :to => 'devise/sessions#new', :as => 'new_user_session'
    post '/login', :to => 'devise/sessions#create'
    delete '/logout', :to => 'devise/sessions#destroy'
    # get '/password/change', :to => 'devise/registrations#edit', :as => 'change_password'
    # TODO: delete the route of cancel account, by delete defaut routes of registrations (:skip => [:registrations]) and only keeping custom ones
    end
  
  resources :users, only: [:index, :show, :edit, :update]

  # Home routes
  root :to => 'home#index'

  namespace :home, :path => nil do
    get :faq
    # get :contact
    # post :contact, :action => :contact_email
    get :site_off
    get :program
    get :about
    get :participants
    get :join
    get :fest2014
    # get :stories
    post :newsletter_collect_email
  end

  resources :stories, :only => [:index, :show], :singular => :story

  namespace :me do
    get :dashboard
    get :preferences
    get :edit_profile   
    get :change_password
    put :apply_change_password
    put :update_profile  
  end

  get '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure' 
    
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    if IndividualType.find_by_title('adesias_videos')      
      @adesias_videos = IndividualType.find_by_title('adesias_videos').get_members
    end      
  end

  def show
    @adesias_video = Individual.find(params[:id])

    @next_video = get_next_video
    @previous_video = get_previous_video

    @next_videos = get_next_videos(3)
  end

  def get_next_videos(video_number)
    @adesias_videos = IndividualType.find_by_title('adesias_videos').get_members
    @next_videos = @adesias_videos.select{|n| n.id > params[:id].to_i}
     
    if !@next_videos.nil? && @next_videos.count >= video_number
      @next_videos.first(video_number)
    else
      @adesias_videos.first(video_number - @next_videos.count).each do |video|
        @next_videos << video
      end
      @next_videos.sort
    end

  end

  def get_next_video
    @adesias_videos = IndividualType.find_by_title('adesias_videos').get_members

    @next_video = @adesias_videos.first(:conditions => ['individuals.id > ?', params[:id]], :order => 'id ASC')

    if !@next_video.nil?
      @next_video
    else
      @adesias_videos.first
    end

  end 

  def get_previous_video
    @adesias_videos = IndividualType.find_by_title('adesias_videos').get_members

    @previous_video = @adesias_videos.last(:conditions => ['individuals.id < ?', params[:id]])

    if !@previous_video.nil?
      @previous_video
    else
      @adesias_videos.last
    end
  end

end

app/views/stories/_header.html.haml
.adesias_header
  .block_header.col-lg-12
    .header_video_name_header.col-lg-8
      = "#" + @adesias_video.first_name
    .back_to_home_header.col-lg-1.col-lg-offset-2
      = link_to image_tag('/assets/adesias/ad_video_btn_retour.png'), stories_path

app/views/stories/index.html.haml
.container{:id =>'adesias_home'}
  .row
    .adesias_header
      .block_header_index.col-lg-12
        .header_video_name_header.col-lg-12
          = "# AGE OF COMMUNITIES"
  .row.adesias_main_content.text-center
    .adesias_main_logo
      = image_tag '/assets/adesias/ad_logo.png'
    .adesias_main_text
      At Adesias, we deeply believe in the collaborative economy, sharing economy, connected economy... whatever the name is! Thanks to the Ouishare team, this already worldwide movement was showcased in Paris at the OUISHAREFEST to discuss  "the age of communities". 
      %br
      %br
      Here are 18 videos to meet the people making this happen. Some big stars, some great speakers, some small entrepreneurs - have a look at our discussions with the inspiring people you could have met if you came!            

  .row.adesias_videos_index.centered
    -if !@adesias_videos.blank?
      .container_list_video_index
        - @adesias_videos.each do |video|
          .col
            %li
              = link_to video.first_name, story_path(video), :id => video.first_name
  .footer

app/views/stories/show.html.haml
.container{:id =>'adesias_home'}
  =render 'header', :adesias_video => @adesias_video
  .video_box.col-lg-12
    .citation
      = image_tag "/assets/adesias/quotes/C_#{@adesias_video.first_name}.png"
    .content.col-lg-12
      .col-left.col-lg-2.col-lg-offset-1.no-padding
        .row
          .video_nav.col-lg-12
            .prev
              = link_to image_tag('/assets/adesias/ad_video_btn_videoprecedente.png'), story_path(@previous_video)
          .post_it.col-lg-12
            = image_tag "/assets/adesias/keywords/post-IT_#{@adesias_video.first_name}.jpg"
      .col-center.col-lg-6.no-padding
        .content_video
          .video_cadre
            %iframe{:style => "margin:90px 25px auto;margin-top:14px;", :allowfullscreen => "", :frameborder => "0", :height => "328", :src => @adesias_video.description, :width => "588"}
          / Mettre le player video à cet endroit
      .col-right.col-lg-2.no-padding
        .video_nav.col-lg-12
          .next
            = link_to image_tag('/assets/adesias/ad_video_btn_videosuivante.png'), story_path(@next_video)
        .visuel.col-lg-12
          = image_tag "/assets/adesias/visuels/Visuels_#{@adesias_video.first_name}.png"

  .sharing_zone.col-lg-12
    .infos.col-lg-5.col-lg-offset-2
      .col-lg-4
        .fb-share-button{"data-href" => @adesias_video.description, "data-type" => "button"}
        %a.twitter-share-button{"data-hashtags" => "OuiShareFest", "data-related" => "adesias", "data-url" => "https://www.youtube.com/watch?v=bnZiMM3EOEc", "data-via" => "ouishare", :href => "https://twitter.com/share"} Tweet
        :javascript
          !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
      .col-lg-8.no-padding
        .vert
          = "-#{@adesias_video.last_name}-"
        - if @adesias_video.twitter_account.present?
          .bleu
            = image_tag "/assets/adesias/ad_twitter.png"
            = link_to @adesias_video.twitter_account, "https://twitter.com/#{@adesias_video.twitter_account}"
    .infos.col-lg-5.col-lg-offset-2
      .vert.info_url
        = link_to @adesias_video.url, @adesias_video.url
    .col-lg-12
      

  .other_video_block.col-lg-12
    .other_video.col-lg-12
      -if !@next_videos.blank?
        .container_list_video_index
          .title
            \#MORE VIDEOS
          - @next_videos.each do |video|
            .col-lg-4.individuals-list-display
              %li
                = link_to video.first_name, story_path(video), :id => video.first_name

  .footer.col-lg-12
  
/ %p
/   %br
/   = link_to image_tag('/assets/adesias/ad_video_btn_videoprecedente.png'), story_path(@previous_video) 
/   = link_to image_tag('/assets/adesias/ad_video_btn_videosuivante.png'), story_path(@next_video) 
/   %br
/   = image_tag '/assets/adesias/quotes/C_' + @adesias_video.first_name + '.png'
/   = image_tag '/assets/adesias/keywords/post-IT_' + @adesias_video.first_name + '.jpg'

/   %p{:style => 'background-image: url(/assets/adesias/ad_video_cadre_video.png); background-repeat:no-repeat;width:640px;height:400px;margin: auto;'}
/     %iframe{:style => "margin:90px 25px auto;margin-top:14px;", :allowfullscreen => "", :frameborder => "0", :height => "328", :src => @adesias_video.description, :width => "588"}     
/     = image_tag '/assets/adesias/visuels/Visuels_' + @adesias_video.first_name + '.png' 

/ / Sharing Zone
/ / Check best practices on https://developers.facebook.com/docs/plugins/checklist/



/ / Zone autres videos
/ %p
/   = image_tag '/assets/adesias/ad_video_zone_autresvideo.png' 
/ -if !@next_videos.blank?
/   .ch-grid
/     - @next_videos.each do |video|
/       .col-lg-4.individuals-list-display
/         %li
/           = link_to video.first_name, story_path(video), :id => video.first_name