config/routes.rb
OuiShareFest::Application.routes.draw do

  resources :traductions
  resources :individual_types

  # SetLanguage routes
  namespace :set_language do
    get :set_new_language, :as => "set_new_language"
  end
  # get 'set_language/set_new_language', :as => "set_new_language"

  # Admin routes
  resources :admin, only: [:index] do
    collection do
      get :export_users
      get :export_newsletter_subscribers
      get :users_list
      get :settings_list 
      get :strong_auth_access_page
      get :individuals_list
      get :individual_types_list
      get :restart_nginx_server
      post :validate_strong_auth    
    end
    member do
      get :individual_type
      post :toggle_admin
      post :toggle_setting
    end
  end

  resources :individuals

  # Devise routes  
  devise_for :users, :skip => [:sessions, :registrations], :path => ''
  devise_scope :user do
    get '/register', :to => 'devise/registrations#new', :as => 'user_registration'
    post '/register', :to => 'devise/registrations#create'
    get '/login', :to => 'devise/sessions#new', :as => 'new_user_session'
    post '/login', :to => 'devise/sessions#create'
    delete '/logout', :to => 'devise/sessions#destroy'
    # get '/password/change', :to => 'devise/registrations#edit', :as => 'change_password'
    # TODO: delete the route of cancel account, by delete defaut routes of registrations (:skip => [:registrations]) and only keeping custom ones
    end
  
  resources :users, only: [:index, :show, :edit, :update]

  # Home routes
  root :to => 'home#index'

  namespace :home, :path => nil do
    get :faq
    # get :contact
    # post :contact, :action => :contact_email
    get :site_off
    get :program
    get :about
    get :participants
    get :join
    get :fest2014
    # get :stories
    post :newsletter_collect_email
  end

  resources :stories, :only => [:index, :show], :singular => :story

  namespace :me do
    get :dashboard
    get :preferences
    get :edit_profile   
    get :change_password
    put :apply_change_password
    put :update_profile  
  end

  get '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure' 
    
end

app/controllers/traductions_controller.rb
class TraductionsController < ApplicationController
  before_filter :authenticate_admin!, :strong_auth
  def index
    @traductions = Translation.all  
    @traduction_keys = Translation.select("DISTINCT(KEY)").order("key ASC")
    
  end

  def show
  end

  def new
    # @availables_languages = I18n.available_locales.sort    
    @availables_languages = I18n.available_locales.select {|locale| locale.to_s == 'en'}
  end

  def create    
    if params[:key].split('.').length == 2
      save_successfull = true    
      params[:value].each do |value|
        if !value[1].blank?
          if !Translation.find_by_locale_and_key(value[0], params[:key])
            translation = {:locale => value[0],
                           :key => params[:key],
                           :value => value[1]
                          }                      
            new_trans = Translation.new(translation)
            
            if !new_trans.save  
              save_successfull=false
            end
          end
        end
      end    
      if save_successfull
        redirect_to traductions_path, :notice => "Trads Succesfully added"
      else
        redirect_to traductions_path, :notice => "An error occured"
      end
    else
      redirect_to :back, :notice => "Please enter a key following this pattern : main_key.sub_key"
    end
  end

  def edit
    @translation = Translation.find(params[:id])
    # @availables_languages = I18n.available_locales.sort
    @availables_languages = I18n.available_locales.select {|locale| locale.to_s == 'en'}
  end

  def update
    save_successfull = true
    @translations = Translation.where(:key => params[:key])    
    params[:value].each do |value|
      translation = @translations.select {|trans| trans.locale == value[0]}
      if !value[1].blank?        
        if translation.count > 0
          if translation.first.value != value[1]
            if !translation.first.update_attributes(:value => value[1])
              save_successfull = false
            end
          end
        else
          translation = {:locale => value[0],
                         :key => params[:key],
                         :value => value[1]
                        }                      
          new_trans = Translation.new(translation)
          if !new_trans.save
            save_successfull = false
          end
        end
      else               
        if translation.count > 0
          if !translation.first.destroy
            save_successfull = false
          end
        end
      end
    end
    if save_successfull
      redirect_to traductions_path, :notice => "Trads Succesfully updated"
    else
      redirect_to traductions_path, :notice => "An error occured"
    end
  end

  def destroy
    @translation = Translation.find(params[:id])
    @translations = Translation.where(:key => @translation.key)
    save_successfull = true

    @translations.each do |translation|
      if !translation.destroy
        save_successfull = false

      end
    end

    if save_successfull
      redirect_to traductions_path, :notice => "Trads Succesfully destroyed"
    else
      redirect_to traductions_path, :notice => "An error occured"
    end
  end  
end

app/helpers/traductions_helper.rb
module TraductionsHelper
end

app/views/traductions/_edit_form.html.haml
= form_tag traduction_path(@translation), :method => :put do |f|
  = hidden_field_tag :key, @translation.key
  .form-group.row
    .col-lg-offset-2.col-lg-10.text-center
      %code
        = @translation.key         
  -@availables_languages.each do |locale|   
    
    - if current_translation = Translation.find_by_key_and_locale(@translation.key, locale.to_s)
      .form-group.row
        .col-lg-2.text-center
          = image_tag "/assets/flags_test/" + locale.to_s + ".png", :width => "32px"
          %span.badge
            = current_translation.locale          
        .col-lg-10
          = text_area_tag :value, current_translation.value, {:class => "form-control", :name => "[value][" + locale.to_s + "]", :size => "25x10"}
    - else
      .form-group.row
        .col-lg-2.text-center
          = image_tag "/assets/flags_test/" + locale.to_s + ".png", :width => "32px"
          %span.badge
            = locale            
        .col-lg-10
          = text_area_tag :value, nil, {:class => "form-control", :name => "[value][" + locale.to_s + "]", :size => "25x10"}
    
  .form-group.row
    .col-lg-offset-2.col-lg-10.text-center
      = submit_tag "Save Trad", :class => "btn btn-success"

app/views/traductions/_new_form.html.haml
= form_tag traductions_path do |f|
  .form-group.row    
    .col-lg-2.text-center
      =label_tag "New Key:"
    .col-lg-10      
      = text_field_tag :key, "", :class => "form-control", :required => true
      %span.help-block
        Please enter a key matching the following pattern: mainkey.subkey
        ex : main.title, footer.subtible ...
  -@availables_languages.each do |locale|   
    .form-group.row
      .col-lg-2.text-center
        = image_tag "/assets/flags_test/" + locale.to_s + ".png", :width => "32px"
        %span.badge
          = locale
      .col-lg-10
        = text_area_tag :value, nil, {:class => "form-control", :name => "[value][" + locale.to_s + "]", :size => "25x10", :required => true}
  .form-group.row
    .col-lg-offset-2.col-lg-10.text-center
      = submit_tag "Save Trad", :class => "btn btn-success"

app/views/traductions/edit.html.haml
%br
.container.admin-container
  .row
    .col-md-3
      = render '/admin/partial/menu', :active => 'traductions'
    .col-md-9  
      %strong    
        %i.glyphicon.glyphicon-edit
        Edit translation key    
        %hr
      =render "edit_form"  
  

app/views/traductions/index.html.haml
%br
.container.admin-container
  .row
    .col-md-3
      = render '/admin/partial/menu', :active => 'traductions'
    .col-md-9    
      %strong
        = link_to new_traduction_path do
          %i.glyphicon.glyphicon-plus-sign
          Create a new translation key
      %hr/
      -@traduction_keys.each do |translation|    
        %p
          - trans_id = Translation.find_by_key(translation.key)
        %table.table
          %thead
            %th.text-center
              %code
                = translation.key
            %th
              %i.glyphicon.glyphicon-edit
              = link_to "Edit", edit_traduction_path(trans_id)
              &nbsp;
              %i.glyphicon.glyphicon-remove
              = link_to "Delete", traduction_path(trans_id), "data-method" => :delete, :confirm => "Are you sure?"
          %tbody
            -Translation.where(:key => translation.key).where(:locale => 'en').each do |translation|
              %tr
                %td.col-md-2.text-center
                  = image_tag "/assets/flags_test/" + translation.locale + ".png", :width => "32px"
                  %span.badge
                    = translation.locale
                %td
                  = translation.value

app/views/traductions/new.html.haml
/ .container
/   %h1 
/     Create a new Traduction
/   = render "new_form"
%br
.container.admin-container
  .row
    .col-md-3
      = render '/admin/partial/menu', :active => 'traductions'
    .col-md-9  
      %strong    
        %i.glyphicon.glyphicon-edit
        Create a new Traduction   
        %hr
      =render "new_form"  